export const root: string;
export const header: string;
export const name: string;
export const occupation: string;
export const iconText: string;
export const contactUrls: string;
export const info: string;
export const qualifications: string;
export const skills: string;
